language: perl
perl:
  - "5.20"

before_install:
  - cpanm Carton

install:
  - carton install

script:
  - carton exec -- prove -lrv t

notifications:
  email:
    recipients:
      - mono@monoweb.info
    on_success: change
    on_failure: always
